# Distributed training of a traditional CNN model to do image classification 
# using the MNIST dataset and PyTorch.
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: pytorch
spec:
  replicatedJobs:
  - name: workers
    template:
      #metadata:
      # labels:
      #   kueue.x-k8s.io/queue-name: dws-local-queue
      # annotations:
       #  provreq.kueue.x-k8s.io/maxRunDurationDays: "7"
      spec:
        parallelism: 2
        completions: 2
        #suspend: true
        backoffLimit: 0
        template:
          metadata:
             annotations:
               gke-gcsfuse/volumes: "true"
          spec:
            #schedulingGates:
            #- name: "gke.io/topology-aware-auto-scheduling-pytorch"
            #restartPolicy: Never # dws
            hostNetwork: true
            dnsPolicy: ClusterFirstWithHostNet
            nodeSelector:
               #cloud.google.com/gke-nodepool: dws-a3-mega #dws
               cloud.google.com/gke-accelerator: nvidia-h100-mega-80gb #non dws
            tolerations:
               - key: "nvidia.com/gpu"
                 operator: "Exists"
                 effect: "NoSchedule"
               - key: user-workload
                 operator: Equal
                 value: "true"
                 effect: NoSchedule
            restartPolicy: Never
            #serviceAccountName: storage-access
            volumes:
            - name: nvidia
              hostPath:
                path: /home/kubernetes/bin/nvidia/lib64
            - name: libraries
              hostPath:
                path: /home/kubernetes/bin/nvidia/lib64
            - name: sys
              hostPath:
                path: /sys
            - name: proc-sys
              hostPath:
                path: /proc/sys
            - name: aperture-devices
              hostPath:
                path: /dev/aperture_devices
            - name: dshm
              emptyDir:
                medium: Memory

            containers:
            - name: tcpxo-daemon
              image: us-docker.pkg.dev/gce-ai-infra/gpudirect-tcpxo/tcpgpudmarxd-dev:v1.0.11
              imagePullPolicy: Always
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -ex
                  chmod 755 /fts/entrypoint_rxdm_container.sh
                  /fts/entrypoint_rxdm_container.sh --num_hops=2 --num_nics=8 --uid= --alsologtostderr
              securityContext:
                privileged: true
              volumeMounts:
                - name: nvidia
                  mountPath: /usr/local/nvidia/lib64
                - name: libraries
                  mountPath: /usr/local/nvidia
                - name: sys
                  mountPath: /hostsysfs
                - name: proc-sys
                  mountPath: /hostprocsysfs
              env:
                - name: LD_LIBRARY_PATH
                  value: /usr/local/nvidia/lib64

            - name: pytorch
              image: us-east1-docker.pkg.dev/northam-ce-mlai-tpu/gke-llm/llama-benchmark:latest
              imagePullPolicy: Always
              # image: gcr.io/k8s-staging-jobset/pytorch-mnist:latest
              ports:
              - containerPort: 3389
              env:           
              - name: MASTER_ADDR
                value: "pytorch-workers-0-0.pytorch"
              - name: MASTER_PORT
                value: "3389"
              - name: NNODES
                value: "2"
              - name: NODE_RANK
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
              # Force python to not buffer output and write directly to stdout, so we can view training logs via `kubectl logs`.
              - name: PYTHONUNBUFFERED
                value: "0"
              
              - name: LD_LIBRARY_PATH
                value: /usr/local/nvidia/lib64
              
              - name: NCCL_FASTRAK_LLCM_DEVICE_DIRECTORY
                value: /dev/aperture_devices
              # - name: TRITON_CACHE_DIR
              #   value: irreverent-datasets/torch-compiler-cache
              securityContext:
                privileged: true
              command:
              - bash
              - -xc
              - |
                NCCL_LIB_DIR="/usr/local/nvidia/lib64"
                source ${NCCL_LIB_DIR}/nccl-env-profile.sh
                python -u -m torch.distributed.run \
                --nproc_per_node 8 \
                --nnodes $NNODES \
                --rdzv_endpoint $MASTER_ADDR:$MASTER_PORT \
                --rdzv_backend c10d \
                --max_restarts 0 \
                --role $MASTER_ADDR: \
                --tee 3 \
                all_reduce_bench.py
              resources:
                requests:
                  #cpu: "8"
                  #memory: "25Gi"
                  #ephemeral-storage: "25Gi"
                  nvidia.com/gpu: 8
                limits:
                  # cpu: "16"
                  # memory: "30Gi"
                  # ephemeral-storage: "30Gi"
                  nvidia.com/gpu: 8
              volumeMounts:
               - name: nvidia
                 mountPath: /usr/local/nvidia/lib64
               - mountPath: /dev/shm
                 name: dshm
               - name: aperture-devices
                 mountPath: /dev/aperture_devices
               
           